### ISSUE TITLE
Arkade dumper core om filnavnet ikke slutter på .tar

### ISSUE THREAD

**Issue by perbu** [arkivverket/arkade5#115]
[Information] Processing archive: /opt/input/2a41d889f209aac1d3f42bc6f6f74956
Unhandled exception. Arkivverket.Arkade.Core.Base.ArkadeException: A file with extension .tar must be selected
   at Arkivverket.Arkade.Core.Base.ArchiveFile.Read(FileInfo archiveFile, ArchiveType archiveType)
   at Arkivverket.Arkade.Core.Base.ArchiveFile.Read(String archiveFile, ArchiveType archiveType)
   at Arkivverket.Arkade.CLI.CommandLineRunner.CreateTestSession(CommandLineOptions options, Arkade arkade, ArchiveType archiveType)
   at Arkivverket.Arkade.CLI.CommandLineRunner.Run(CommandLineOptions options)
   at Arkivverket.Arkade.CLI.Program.RunOptionsAndReturnExitCode(CommandLineOptions options)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at Arkivverket.Arkade.CLI.Program.Main(String[] args)
Aborted (core dumped)

1.5.0.

Arkade burde ikke bry seg om hva filnavnet er. Den burde iallefall ikke feile med en stack trace og dumpe core.

**Comment by erikaaberg** [comment]
Fixet.
