### ISSUE TITLE
Flate filer/fagsystem - Bruk av datoformat YYYY-MM-DD feiler

### ISSUE THREAD

**Issue by Viken-Petter** [arkivverket/arkade5#140]
Arkade 5 versjon 2.7.0

Feiler i ControlDataFormat.

Feilmelding i Arkade 5 (error-log):

"
Stack trace:
System.ArgumentOutOfRangeException: Index and length must refer to a location within the string. (Parameter 'length')
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Arkivverket.Arkade.Core.Base.Addml.Definitions.DataTypes.DateDataType.ConvertIso8601CalendarDateTimeStringToCSharpDateTimeString(String iso8601DateTimeString) in (..)\Arkivverket.Arkade.Core\Base\Addml\Definitions\DataTypes\DateDataType.cs:line 109
   at Arkivverket.Arkade.Core.Base.Addml.Definitions.DataTypes.DateDataType.IsValid(String s) in (..)\Arkivverket.Arkade.Core\Base\Addml\Definitions\DataTypes\DateDataType.cs:line 86
   at Arkivverket.Arkade.Core.Base.Addml.Processes.A_19_ControlDataFormat.DoRun(Field field) in (..)\Arkivverket.Arkade.Core\Base\Addml\Processes\A_19_ControlDataFormat.cs:line 88
   at Arkivverket.Arkade.Core.Base.Addml.Processes.AddmlProcess.Run(Field field, Int64 recordNumber) in (..)\Arkivverket.Arkade.Core\Base\Addml\Processes\AddmlProcess.cs:line 57
   at Arkivverket.Arkade.Core.Base.Addml.FieldProcessRunner.RunProcesses(Field field, Int64 recordNumber) in (..)\Arkivverket.Arkade.Core\Base\Addml\FieldProcessRunner.cs:line 22
   at Arkivverket.Arkade.Core.Base.Addml.AddmlDatasetTestEngine.RunTestsOnArchive(TestSession testSession) in (..)\Arkivverket.Arkade.Core\Base\Addml\AddmlDatasetTestEngine.cs:line 86
   at Arkivverket.Arkade.Core.Base.ArkadeApi.RunTests(TestSession testSession) in (..)\Arkivverket.Arkade.Core\Base\ArkadeApi.cs:line 94
   at Arkivverket.Arkade.GUI.ViewModels.TestRunnerViewModel.RunTests() in (..)\Arkivverket.Arkade.GUI\ViewModels\TestRunnerViewModel.cs:line 426
"

Vedlagt Arkade-feillogg og ymse skjermbilder.
[arkade-error-20220822090924.log](https://github.com/arkivverket/arkade5/files/9392351/arkade-error-20220822090924.log)
![Skjermbilde_addml_xml](https://user-images.githubusercontent.com/86402326/185867945-e39d0019-d8e8-484b-985e-d474e9180f36.PNG)
![Skjermbilde_Arkade5](https://user-images.githubusercontent.com/86402326/185867951-ebccd9a4-069a-4983-b050-873ce28224c4.PNG)
![Skjermbilde_data](https://user-images.githubusercontent.com/86402326/185867952-6719b6d3-5e79-4e6d-9298-e2f529ebe5fc.PNG)

**Comment by erikaaberg** [comment]
Lagt inn som task i vår Jira.

**Comment by erikaaberg** [comment]
Dett er rettet i versjon 2.8.0
