### ISSUE TITLE
Arkade5 2.9.1 (og tidligere) feiler om filer har created, modified eller accessed date som må konverteres til en signed 32bit integer

### ISSUE THREAD

**Issue by Swoy** [arkivverket/arkade5#166]
Som i tittelen, om en fil har en dato som konverteres til f.eks -2082844800 (01.01.1904 kl. 00.00.00), så feiler Arkade5 i pakkeprosessen med følgende (korte og brutale) stacktrace:

```
Stack trace:
System.ArgumentOutOfRangeException: ModTime cannot be before Jan 1st 1970 (Parameter 'value')
   at ICSharpCode.SharpZipLib.Tar.TarHeader.set_ModTime(DateTime value)
   at ICSharpCode.SharpZipLib.Tar.TarEntry.GetFileTarHeader(TarHeader header, String file)
   at ICSharpCode.SharpZipLib.Tar.TarEntry.CreateEntryFromFile(String fileName)
   at Arkivverket.Arkade.Core.Base.InformationPackageCreator.AddFilesInDirectory(Archive archive, DirectoryInfo directory, DirectoryInfo rootDirectory, Nullable`1 packageType, TarArchive tarArchive, String fileNamePrefix) in (..)\Arkivverket.Arkade.Core\Base\InformationPackageCreator.cs:line 184
   at Arkivverket.Arkade.Core.Base.InformationPackageCreator.AddFilesInDirectory(Archive archive, DirectoryInfo directory, DirectoryInfo rootDirectory, Nullable`1 packageType, TarArchive tarArchive, String fileNamePrefix) in (..)\Arkivverket.Arkade.Core\Base\InformationPackageCreator.cs:line 193
   at Arkivverket.Arkade.Core.Base.InformationPackageCreator.AddFilesInDirectory(Archive archive, DirectoryInfo rootDirectory, Nullable`1 packageType, TarArchive tarArchive, String fileNamePrefix) in (..)\Arkivverket.Arkade.Core\Base\InformationPackageCreator.cs:line 169
   at Arkivverket.Arkade.Core.Base.InformationPackageCreator.CreatePackage(PackageType packageType, Archive archive, ArchiveMetadata metadata, String outputDirectory) in (..)\Arkivverket.Arkade.Core\Base\InformationPackageCreator.cs:line 80
   at Arkivverket.Arkade.Core.Base.InformationPackageCreator.CreateSip(Archive archive, ArchiveMetadata metadata, String outputDirectory) in (..)\Arkivverket.Arkade.Core\Base\InformationPackageCreator.cs:line 37
   at Arkivverket.Arkade.Core.Base.ArkadeApi.CreatePackage(TestSession testSession, String outputDirectory) in (..)\Arkivverket.Arkade.Core\Base\ArkadeApi.cs:line 127
   at Arkivverket.Arkade.GUI.ViewModels.CreatePackageViewModel.CreatePackageRunEngine(String outputDirectory) in (..)\Arkivverket.Arkade.GUI\ViewModels\CreatePackageViewModel.cs:line 485
```

Legg merke til `ModTime cannot be before Jan 1st 1970 (Parameter 'value')`. Det ser ut som dette skjer i SSharpZipLib når den forsøker å sette modtime på filen i pakken. Dette er ren spekulasjon, men kan det være at biblioteket rett og slett ikke håndterer signed integers?

Jeg forsøkte med en fil og satt den til en dato innenfor området til epoch men som krever signed 32 bit.

![image](https://user-images.githubusercontent.com/5272077/236457558-16a95f9c-e672-418c-bdc9-015e8f1f5b3f.png)

**Comment by joergen-vs** [comment]
https://github.com/icsharpcode/SharpZipLib/blob/0ef794188009c17465e6444d9cf9fffd36eae6e7/src/ICSharpCode.SharpZipLib/Tar/TarHeader.cs#L350

**Comment by Swoy** [comment]
Vil følge opp denne. Ble dette fikset i 2.10?

**Comment by Swoy** [comment]
Hei, jeg følger denne opp igjen. Er det noen som kan svare på dette? Vi har fått spørsmål fra Riksantikvarens leverandører om de kan begynne en operasjon som krever at dette er gjort ^^
