### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by erikaaberg** [arkivverket/arkade5#71]
Denne dukker opp igjen. (Versjon 06.41)

Stack trace:
Stack trace:

 

System.NullReferenceException: Object reference not set to an instance of an object.

 

   at Arkivverket.Arkade.Tests.Noark5.NumberOfEachDocumentStatus.GetTestResults() in C:\dev\TeamCity\buildAgent\work\6ce877c8820389f\src\Arkivverket.Arkade\Tests\Noark5\NumberOfEachDocumentStatus.cs:line 53

 

   at Arkivverket.Arkade.Core.Noark5.Noark5BaseTest.GetTestRun() in C:\dev\TeamCity\buildAgent\work\6ce877c8820389f\src\Arkivverket.Arkade\Core\Noark5\Noark5BaseTest.cs:line 33

 

   at Arkivverket.Arkade.Core.Noark5.Noark5TestEngine.AddTestToTestSuite(IEnumerable`1 tests, TestSuite testSuite) in C:\dev\TeamCity\buildAgent\work\6ce877c8820389f\src\Arkivverket.Arkade\Core\Noark5\Noark5TestEngine.cs:line 46

 

   at Arkivverket.Arkade.Core.Noark5.Noark5TestEngine.RunTestsOnArchive(TestSession testSession) in C:\dev\TeamCity\buildAgent\work\6ce877c8820389f\src\Arkivverket.Arkade\Core\Noark5\Noark5TestEngine.cs:line 33

 

   at Arkivverket.Arkade.Core.ArkadeApi.RunTests(TestSession testSession) in C:\dev\TeamCity\buildAgent\work\6ce877c8820389f\src\Arkivverket.Arkade\Core\ArkadeApi.cs:line 47

 

   at Arkivverket.Arkade.UI.ViewModels.TestRunnerViewModel.RunTests() in C:\dev\TeamCity\buildAgent\work\6ce877c8820389f\src\Arkivverket.Arkade.UI\ViewModels\TestRunnerViewModel.cs:line 241

**Comment by erikaaberg** [comment]
Fixet.
