### ISSUE TITLE
Får ikke lagd rapport, feilmeldingen sier ikke hva som gjør at det feiler

### ISSUE THREAD

**Issue by oddbjorn-hansen** [arkivverket/arkade5#92]
System information:
Arkade version: 1.3.1.0
.NET CLR: 4.0.30319.42000
Total disk space: 160691122176 (153246 MB)
Available disk space: 56107393024 (53508 MB)

Stack trace:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Arkivverket.Arkade.Core.Testing.Noark5.NumberOfEachDocumentStatus.GetTestResults()
   at Arkivverket.Arkade.Core.Base.Noark5.Noark5BaseTest.GetTestRun()
   at Arkivverket.Arkade.Core.Base.Noark5.Noark5TestEngine.AddTestToTestSuite(IEnumerable`1 tests, TestSuite testSuite)
   at Arkivverket.Arkade.Core.Base.Noark5.Noark5TestEngine.RunTestsOnArchive(TestSession testSession)
   at Arkivverket.Arkade.Core.Base.ArkadeApi.RunTests(TestSession testSession)
   at Arkivverket.Arkade.GUI.ViewModels.TestRunnerViewModel.RunTests() in C:\dev\TeamCity\buildAgent\work\a0525764e1ed6c7e\src\Arkivverket.Arkade.GUI\ViewModels\TestRunnerViewModel.cs:line 284

**Comment by joergen-vs** [comment]
Blir arkivstruktur.xml validert?

**Comment by oddbjorn-hansen** [comment]
Feilen kommer under valideringen så vidt jeg kan se.

**Comment by joergen-vs** [comment]
Er rimelig sikker på hvor i Arkade feilen forekommer, vet bare ikke om en smart måte å finne hvor i dataene den forekommer.
Det ser for meg ut som det finnes journalposttype-felt [M082] uten verdi. Du kan alltids prøve å validere filene med en endret metadatakatalog.xsd, hvor du bytter ut

```xml
  <xs:simpleType name="journalposttype">
    <xs:annotation>
      <xs:documentation>M082</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string"/>
  </xs:simpleType>
```

med

```xml
  <xs:simpleType name="journalposttype">
    <xs:annotation>
      <xs:documentation>M082</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:minLength value="1"/>
    </xs:restriction>
  </xs:simpleType>
```

Ellers ligger saken allerede aktiv hos en utvikler, så den skal være løst i neste utgave av Arkade 5.

**Comment by erikaaberg** [comment]
Vi tror denne feilen er rettet - - -
